server:
  port: 8080

spring:
  datasource:
    url: ${DB_POSTGRES_URL:jdbc:postgresql://localhost:5432/spring_template_db?sslmode=disable}
    username: ${DB_POSTGRES_USERNAME:user_admin}
    password: ${DB_POSTGRES_PASSWORD:password_secret}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false  # Turn off Open Session in View to prevent LazyInitializationException in web applications

  docker:
    compose:
      enabled: true
      file: docker-compose.yaml