spring:
  datasource:
    url: jdbc:h2:mem:cleanproject_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE #Using H2 with postgreSQL compatibility mode for testing
    username: sa
    password:
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate

  docker:
    compose:
      enabled: false
